language: python
python:
  - "3.8"

services:
  - docker

env:
  global:
    - ELASTICSEARCH_URL=http://localhost:9200

before_install:
  - sudo apt-get update
  - sudo apt-get install -y docker.io

before_script:
  - docker-compose up -d

install:
  - pip install -r requirements.txt

script:
  - pytest

after_script:
  - docker-compose down
