name: 🤗 Sync to HuggingFace Space

on:
  push:
    branches: [main]

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      # Push to hub
      - name: Push to hub
        env:
          HF_USER: ${{ secrets.HF_USER }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_REPO: ${{ secrets.HF_REPO }}
        run: git push -f https://$HF_USER:$HF_TOKEN@huggingface.co/spaces/$HF_USER/$HF_REPO main
